---
# setup-microshift-host default vars

go_arch: arm64
go_files:
  - go
  - gofmt
go_version: 1.20.3
go_install_dir: /usr/local/go{{ go_version }}

install_packages:
  - bash-completion
  - firewalld
  - git
  - golang
  - jq
  - lvm2
  - make
  - openshift-clients
  - python3-firewall
  - perf
  - rpm-build
  - selinux-policy-devel 
  - tar
  - vnstat

vg_name: rhel
lvm_disk: /dev/xvdb
