---
# setup-localhost tasks
#

- name: cleanup existing known_hosts entries
  ansible.builtin.lineinfile:
    path: ~/.ssh/known_hosts
    state: absent
    regexp: "{{ item }}"
  loop: "{{ known_hosts }}"

- name: wait 300 seconds for port 22 to become open and contain "OpenSSH"
  ansible.builtin.wait_for:
    port: 22
    host: "{{ item }}"
    search_regex: OpenSSH
  with_inventory_hostnames:
    - all

- name: write the new ssh fingerprint to known hosts
  ansible.builtin.shell: "ssh-keyscan {{ item }} >> ~/.ssh/known_hosts"
  with_inventory_hostnames:
    - all

- name:
  ansible.builtin.command: sshpass -p {{ microshift_pass }} ssh-copy-id {{ ansible_user }}@{{ item }}
  with_inventory_hostnames:
    - microshift

- name: install local ansible prereq pacakges
  ansible.builtin.dnf:
    name: "{{ local_packages }}"
    state: present
    update_cache: true
  when: (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat") or (ansible_distribution == "Fedora")
  become: yes
