kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:router
rules:
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes/status
  verbs:
  - update
