apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: lvms-operator-metrics-cert
  creationTimestamp: null
  labels:
    app.kubernetes.io/compose: metrics
    app.kubernetes.io/name: lvms-operator
  name: lvms-operator-metrics-service
  namespace: openshift-storage
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app.kubernetes.io/name: lvms-operator
status:
  loadBalancer: {}
