apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vg-manager
  namespace: openshift-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vg-manager
  namespace: openshift-storage
subjects:
- kind: ServiceAccount
  name: vg-manager
  namespace: openshift-storage
