kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: multus
  namespace: openshift-multus
  annotations:
    kubernetes.io/description: |
      This daemonset launches the Multus networking component on each node.
spec:
  selector:
    matchLabels:
      app: multus
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        app: multus
        component: network
        type: infra
        openshift.io/component: network
        kubernetes.io/os: "linux"
    spec:
      serviceAccountName: multus
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: "system-node-critical"
      tolerations:
      - operator: Exists
      initContainers:
      - name: install-container-network-plugins
        image: containernetworking-plugins-microshift
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-ec", "--" ]
        args:
          - >
            /entrypoint/cnibincopy.sh;
        volumeMounts:
        - name: cnibin
          mountPath: /host/run/cni/bin
        - mountPath: /entrypoint
          name: cni-binary-copy
        env:
        - name: DEFAULT_SOURCE_DIRECTORY
          value: "/usr/src/plugins/bin/"
        - name: BINARIES_TO_COPY
          value: "{bridge,ipvlan,macvlan,static,dhcp,host-local}"
      containers:
      - name: kube-multus
        image: multus-cni-microshift
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-ec", "--" ]
        args:
          - >
            /entrypoint/cnibincopy.sh;
            echo "$(date --iso-8601=seconds) Waiting for /etc/cni/net.d/10-ovn-kubernetes.conf";
            start=$(date +%s);
            while [ ! -f /host/etc/cni/net.d/10-ovn-kubernetes.conf ]; do
              now=$(date +%s);
              if $(( now - start > 5 * 60 )); then
                echo "$(date --iso-8601=seconds) Timed out waiting for /etc/cni/net.d/10-ovn-kubernetes.conf";
                exit 1;
              fi;
              sleep 2;
            done;
            echo "$(date --iso-8601=seconds) /etc/cni/net.d/10-ovn-kubernetes.conf exists - proceeding";
            exec /usr/src/multus-cni/bin/thin_entrypoint
            --multus-conf-file=auto
            --cni-bin-dir=/host/run/cni/bin
            --multus-autoconfig-dir=/host/etc/cni/net.d
            --readiness-indicator-file=/etc/cni/net.d/10-ovn-kubernetes.conf
            --cleanup-config-on-exit=true
            --skip-multus-binary-copy=true
        resources:
          requests:
            cpu: 10m
            memory: 65Mi
        securityContext:
          privileged: true
        lifecycle:
          preStop:
            exec:
              # Following doesn't work too well until multus daemonset
              # starts to sleep between config/kubeconfig checks as
              # these files might get recreated before thin_entrypoint exits.
              #
              # preStop hook can't access `env` so plugins are directly hardcoded.
              command:
              - "/bin/bash"
              - "-c"
              - >
                rm -vf /host/etc/cni/net.d/00-multus.conf* > /proc/1/fd/1 2>&1;
                rm -vfr /host/etc/cni/net.d/multus.d > /proc/1/fd/1 2>&1;
        volumeMounts:
        - mountPath: /entrypoint
          name: cni-binary-copy
        - name: system-cni-dir
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /host/run/cni/bin
        env:
        - name: DEFAULT_SOURCE_DIRECTORY
          value: "/usr/src/multus-cni/bin/"
        - name: BINARIES_TO_COPY
          value: "multus"
      terminationGracePeriodSeconds: 10
      volumes:
        - name: system-cni-dir
          hostPath:
            path: "/etc/cni/net.d"
            type: Directory
        - name: cnibin
          hostPath:
            path: "/run/cni/bin"
            type: DirectoryOrCreate
        - name: run
          hostPath:
            path: "/run"
            type: Directory
        - name: cni-binary-copy
          configMap:
            name: cni-copy-resources
            defaultMode: 0744
