---
# Setup Microshfit nodes
#
# Example Usage:
#
# ansible-playbook -i inventory/inventory setup-node.yml
#

- name: create vm and set up localhost
  hosts: localhost
  vars:
    become: no
    ansible_connection: local
  vars_files:
  - vars/all.yml
  roles:
    - role: create-vm
      when: (create_devenv | bool)
    - role: setup-localhost

- name: set up logging node
  hosts: logging
  become: yes
  vars_files:
  - vars/all.yml
  roles:
    - role: install-logging
      when: (prometheus_logging | bool)

- name: entitle host and manage repos
  hosts: microshift
  become: yes
  vars_files:
    - vars/all.yml
  roles:
    - role: manage-repos
      when: (manage_repos | bool)

- name: install packages, configure services & firewall
  hosts: microshift
  become: yes
  vars_files:
    - vars/all.yml
  roles:
    - role: setup-microshift-host
      when: (setup_microshift_host | bool)
    - role: configure-firewall
      when: (setup_microshift_host | bool)
    - role: install-logging-exporters
      when: (prometheus_logging | bool)

- name: install microshift
  hosts: microshift
  vars_files:
    - vars/all.yml
  roles:
    - role: install-microshift
      when: (install_microshift | bool)

- name: capture microshift metrics
  hosts: microshift
  vars_files:
    - vars/all.yml
  roles:
    - role: microshift-start

- name: add kubelet endpoint to prometheus
  hosts: logging
  become: yes
  gather_facts: no
  vars_files:
    - vars/all.yml
  roles:
    - role: add-kubelet-logging

- name: pull kubeconfig from microshift host
  hosts: microshift
  vars_files:
    - vars/all.yml
  roles:
    - role: fetch-kubeconfig

- name: run performance workloads
  hosts: localhost
  vars:
    ansible_become: no
    ansible_connection: local
  vars_files:
    - vars/all.yml
  roles:
    - role: run-workloads
